/**
 * Comet Framework - Feature Module Registry (Auto-Generated)
 * DO NOT EDIT - This file is automatically generated by the build system
 * Add new features by creating folders in src/features/
 * @module @voilajsx/comet
 * @file src/features/index.js
 */

// ============================================================================
// 🚀 AUTO-DISCOVERED FEATURES - Generated at build time
// ============================================================================

export { default as pageAnalyzer } from './page-analyzer/index.js';
export { default as quoteGenerator } from './quote-generator/index.js';

// ============================================================================
// Total features: 2
// Last generated: 2025-06-21T04:43:38.150Z
// ============================================================================
