/**
 * Comet Framework - Feature Module Registry (Auto-Generated)
 * DO NOT EDIT - This file is automatically generated by the build system
 * Add new features by creating folders in src/features/
 * 
 * 🎛️  SIMPLE FEATURE TOGGLE:
 * ✅ Enable:  Remove underscore from folder name (feature-name)
 * ❌ Disable: Add underscore to folder name (_feature-name)
 * 🔄 Apply:   Auto-detects folder renames in dev mode!
 * 
 * @module @voilajsx/comet
 * @file src/features/index.ts
 */

// Type definitions for feature modules
export interface HandlerFunction {
  (data?: any, sender?: chrome.runtime.MessageSender): any | Promise<any>;
}

export interface PopupTabConfig {
  label: string;
  icon: string;
  order: number;
  requiresTab?: boolean;
  description?: string;
}

export interface OptionsPanelConfig {
  label: string;
  icon: string;
  section?: string;
  order: number;
  description?: string;
}

export interface FeatureUI {
  popup?: {
    tab: PopupTabConfig;
    component: () => Promise<{ default: React.ComponentType<any> }>;
  };
  options?: {
    panel: OptionsPanelConfig;
    component: () => Promise<{ default: React.ComponentType }>;
  };
}

export interface SettingSchema {
  key: string;
  default: any;
  type: 'boolean' | 'string' | 'number' | 'select';
  label: string;
  description?: string;
  options?: Array<{ value: string; label: string }>;
}

export interface FeatureMeta {
  name: string;
  description: string;
  version: string;
  author?: string;
  category?: string;
  tags?: string[];
  permissions?: string[];
}

export interface FeatureLifecycle {
  onEnable?: () => void | Promise<void>;
  onDisable?: () => void | Promise<void>;
  onSettingsChange?: (changes: any) => void | Promise<void>;
}

export interface ModuleConfig {
  name: string;
  ui?: FeatureUI;
  settings?: Record<string, SettingSchema>;
  meta?: FeatureMeta;
  handlers?: Record<string, HandlerFunction>;
  mainAction?: HandlerFunction;
  analyze?: HandlerFunction;
  init?: () => void | Promise<void>;
  lifecycle?: FeatureLifecycle;
}

// ============================================================================
// 🚀 AUTO-DISCOVERED ACTIVE FEATURES - Generated at build time
// ============================================================================

export { default as pageAnalyzer } from './page-analyzer/index.js';
export { default as quoteGenerator } from './quote-generator/index.js';
export { default as weatherWidget } from './weather-widget/index.js';

// ============================================================================
// 💤 DISABLED FEATURES (underscore prefix)
// To enable any feature: Remove underscore from folder name
// ============================================================================
// _website-screenshot (disabled - remove underscore to enable)



// ============================================================================
// Total features: 3
// Disabled features: 1
// Last generated: 2025-06-22T05:05:39.726Z
// 
// 🚀 Quick Commands:
// Enable feature:  mv src/features/_feature-name src/features/feature-name
// Disable feature: mv src/features/feature-name src/features/_feature-name
// ✨ Changes auto-detected in dev mode!
// ============================================================================
